name: Command Consistency Check

on:
  pull_request:
    paths:
      - '.claude/commands/**'
      - 'scripts/validate-command-consistency.ts'
      - 'scripts/__tests__/validate-command-consistency*.ts'
  push:
    branches:
      - main
    paths:
      - '.claude/commands/**'
      - 'scripts/validate-command-consistency.ts'

jobs:
  validate:
    name: Validate Command Consistency
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run command validation
        run: npm run validate:commands

      - name: Comment on PR (if failure)
        if: failure() && github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '❌ **Command Consistency Validation Failed**\n\nThe command consistency check detected issues. Please review the errors in the workflow logs and update the affected commands to ensure consistency.\n\n**Common fixes:**\n- Add missing required terms to command files\n- Update examples to match current patterns\n- Ensure terminology is consistent across commands\n\n**Documentation**: [Architectural Change Checklist](https://github.com/' + context.repo.owner + '/' + context.repo.repo + '/blob/main/docs/processes/architectural-change-checklist.md)'
            })
